echo "******准备代码******"
echo GERRIT_EVENT_TYPE=${GERRIT_EVENT_TYPE}
echo GERRIT_EVENT_HASH=${GERRIT_EVENT_HASH}
echo GERRIT_BRANCH=${GERRIT_BRANCH}
echo GERRIT_TOPIC=${GERRIT_TOPIC}
echo GERRIT_CHANGE_NUMBER=${GERRIT_CHANGE_NUMBER}
echo GERRIT_CHANGE_ID=${GERRIT_CHANGE_ID}
echo GERRIT_PATCHSET_NUMBER=${GERRIT_PATCHSET_NUMBER}
echo GERRIT_PATCHSET_REVISION=${GERRIT_PATCHSET_REVISION}
echo GERRIT_REFSPEC=${GERRIT_REFSPEC}
echo GERRIT_PROJECT=${GERRIT_PROJECT}
echo GERRIT_CHANGE_SUBJECT=${GERRIT_CHANGE_SUBJECT}
echo GERRIT_CHANGE_COMMIT_MESSAGE=${GERRIT_CHANGE_COMMIT_MESSAGE}
echo GERRIT_CHANGE_URL=${GERRIT_CHANGE_URL}
echo GERRIT_CHANGE_OWNER=${GERRIT_CHANGE_OWNER}
echo GERRIT_CHANGE_OWNER_NAME=${GERRIT_CHANGE_OWNER_NAME}
echo GERRIT_CHANGE_OWNER_EMAIL=${GERRIT_CHANGE_OWNER_EMAIL}
echo GERRIT_PATCHSET_UPLOADER=${GERRIT_PATCHSET_UPLOADER}
echo GERRIT_PATCHSET_UPLOADER_NAME=${GERRIT_PATCHSET_UPLOADER_NAME}
echo GERRIT_PATCHSET_UPLOADER_EMAIL=${GERRIT_PATCHSET_UPLOADER_EMAIL}
echo GERRIT_NAME=${GERRIT_NAME}
echo GERRIT_HOST=${GERRIT_HOST}
echo GERRIT_PORT=${GERRIT_PORT}
echo GERRIT_SCHEME=${GERRIT_SCHEME}
echo GERRIT_VERSION=${GERRIT_VERSION}
java -version

function git_cherry_pick_fetch_head(){
	__msg=`git cherry-pick -n FETCH_HEAD`
	echo 
}


cd $WORKSPACE
#rm -rf ${GERRIT_PROJECT}
mkdir -p ${GERRIT_PROJECT}
cd ${GERRIT_PROJECT}
git init
git -c core.askpass=true fetch --tags --progress ${GERRIT_NAME}:${GERRIT_PROJECT} +refs/heads/*:refs/remotes/origin/*
git fetch ${GERRIT_NAME}:${GERRIT_PROJECT} $GERRIT_REFSPEC
git checkout --orphan sonar
git reset --hard
rm -rf *
$(git_cherry_pick_fetch_head)
#git rm -rf --ignore-unmatch *



